name: univagenda
description: Application pour voir son agenda universitaire Ã  tout moment et facilement.
version: 5.0.0+20240918
publish_to: "none"

environment:
  sdk: ^3.4.0
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  after_layout: 1.2.0
  collection: 1.18.0
  firebase_analytics: 11.2.1
  firebase_core: 3.3.0
  firebase_crashlytics: 4.0.4
  flutter_markdown: 0.7.3
  flutter_material_color_picker: 1.2.0
  flutter_timezone: 3.0.1
  html: 0.15.4
  http: 1.2.2
  icalendar_parser: 2.0.0
  image_picker: 1.1.2
  intl: 0.19.0
  introduction_screen: 3.1.14
  mobile_scanner: 5.2.3
  package_info_plus: 8.0.2
  path_provider: 2.1.4
  permission_handler: 11.3.1
  provider: 6.1.2
  shared_preferences: 2.3.2
  syncfusion_flutter_calendar: 27.1.48
  syncfusion_localizations: 27.1.48
  timezone: 0.9.4
  url_launcher: 6.3.0
  uuid: 4.5.0
  material_color_utilities: 0.11.1

dev_dependencies:
  dependency_validator: 4.1.0
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true

  assets:
    - res/images/
    - res/locales/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: res/fonts/GoogleSans-Regular.ttf
          style: normal
          weight: 500

        - asset: res/fonts/GoogleSans-Medium.ttf
          style: normal
          weight: 600

        - asset: res/fonts/GoogleSans-Bold.ttf
          style: normal
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "res/images/icon_circle.png"
  image_path_ios: "res/images/icon_ios.png"
  adaptive_icon_background: "#FFFF0000"
  adaptive_icon_foreground: "res/images/icon_foreground.png"
